### ISSUE TITLE
بزرگ بودن توابع و اجرا نکردن کامل اصول کلین کد

### ISSUE THREAD

**Issue by mhaghighat20** [backendinternship/neginjfi#1]

**Comment by mhaghighat20** [comment]
مثلا تابع مین بزرگ هست و می تونه به چند تابع شکسته بشه
همچنین میشه مثل این ریپو طراحی بهتری داشت:
https://github.com/backendinternship/yasharzb/tree/master/src/

**Comment by Negin-Jafari** [comment]
کد نهایی و ریفکتور شده پوش شد .
ممنون از توجه
